export type StickerCategoryId =
  | "all"
  | "hearts"
  | "flowers"
  | "party"
  | "wedding"
  | "graduation"
  | "birthday"
  | "baby"
  | "nature"
  | "stars"
  | "ornament";

export type StickerKind = "sticker" | "ornament";

export interface StockSticker {
  id: string;
  title: string;
  category: Exclude<StickerCategoryId, "all">;
  keywords: string;
  url: string;
  sourceUrl: string;
  set: "fluent-emoji" | "lucide";
  icon: string;
  kind: StickerKind;
}

export const STICKER_CATEGORIES: { id: StickerCategoryId; label: string }[] = [
  { id: "all", label: "Tất cả" },
  { id: "hearts", label: "Trái tim" },
  { id: "flowers", label: "Hoa" },
  { id: "party", label: "Tiệc" },
  { id: "wedding", label: "Cưới" },
  { id: "graduation", label: "Tốt nghiệp" },
  { id: "birthday", label: "Sinh nhật" },
  { id: "baby", label: "Baby" },
  { id: "nature", label: "Thiên nhiên" },
  { id: "stars", label: "Sao & lấp lánh" },
];

export const ORNAMENT_CATEGORIES: { id: StickerCategoryId; label: string }[] = [
  { id: "all", label: "Tất cả" },
  { id: "ornament", label: "Họa tiết" },
];

function fluent(name: string): string {
  return `https://api.iconify.design/fluent-emoji/${name}.svg?height=128`;
}

function lucide(name: string): string {
  return `https://api.iconify.design/lucide/${name}.svg?height=128&color=%232D231F`;
}

function item(
  id: string,
  title: string,
  category: StockSticker["category"],
  keywords: string,
  set: StockSticker["set"],
  icon: string,
): StockSticker {
  return {
    id,
    title,
    category,
    keywords,
    set,
    icon,
    sourceUrl: set === "lucide" ? lucide(icon) : fluent(icon),
    url: `/stickers/${category}/${id}.png`,
    kind: category === "ornament" ? "ornament" : "sticker",
  };
}

export const STOCK_STICKERS: StockSticker[] = [
  item(
    "heart-red",
    "Tim đỏ",
    "hearts",
    "tim heart love",
    "fluent-emoji",
    "red-heart",
  ),
  item(
    "heart-pink",
    "Tim hồng",
    "hearts",
    "tim heart",
    "fluent-emoji",
    "pink-heart",
  ),
  item(
    "heart-orange",
    "Tim cam",
    "hearts",
    "tim heart",
    "fluent-emoji",
    "orange-heart",
  ),
  item(
    "heart-yellow",
    "Tim vàng",
    "hearts",
    "tim heart",
    "fluent-emoji",
    "yellow-heart",
  ),
  item(
    "heart-green",
    "Tim xanh lá",
    "hearts",
    "tim heart",
    "fluent-emoji",
    "green-heart",
  ),
  item(
    "heart-blue",
    "Tim xanh",
    "hearts",
    "tim heart",
    "fluent-emoji",
    "blue-heart",
  ),
  item(
    "heart-purple",
    "Tim tím",
    "hearts",
    "tim heart",
    "fluent-emoji",
    "purple-heart",
  ),
  item(
    "heart-white",
    "Tim trắng",
    "hearts",
    "tim heart white",
    "fluent-emoji",
    "white-heart",
  ),
  item(
    "heart-brown",
    "Tim nâu",
    "hearts",
    "tim heart brown",
    "fluent-emoji",
    "brown-heart",
  ),
  item(
    "heart-light-blue",
    "Tim xanh nhạt",
    "hearts",
    "tim heart",
    "fluent-emoji",
    "light-blue-heart",
  ),
  item(
    "heart-grey",
    "Tim xám",
    "hearts",
    "tim heart",
    "fluent-emoji",
    "grey-heart",
  ),
  item(
    "heart-two",
    "Hai tim",
    "hearts",
    "tim heart",
    "fluent-emoji",
    "two-hearts",
  ),
  item(
    "heart-sparkle",
    "Tim lấp lánh",
    "hearts",
    "tim sparkle",
    "fluent-emoji",
    "sparkling-heart",
  ),
  item(
    "heart-grow",
    "Tim lớn dần",
    "hearts",
    "tim",
    "fluent-emoji",
    "growing-heart",
  ),
  item(
    "heart-beat",
    "Tim đập",
    "hearts",
    "tim",
    "fluent-emoji",
    "beating-heart",
  ),
  item(
    "heart-ribbon",
    "Tim nơ",
    "hearts",
    "tim no",
    "fluent-emoji",
    "heart-with-ribbon",
  ),
  item(
    "heart-arrow",
    "Tim mũi tên",
    "hearts",
    "tim",
    "fluent-emoji",
    "heart-with-arrow",
  ),
  item(
    "heart-fire",
    "Tim lửa",
    "hearts",
    "tim fire",
    "fluent-emoji",
    "heart-on-fire",
  ),
  item(
    "heart-revolve",
    "Tim xoay",
    "hearts",
    "tim revolving",
    "fluent-emoji",
    "revolving-hearts",
  ),
  item(
    "heart-mend",
    "Tim hàn gắn",
    "hearts",
    "tim mend",
    "fluent-emoji",
    "mending-heart",
  ),
  item(
    "heart-deco",
    "Họa tiết tim",
    "hearts",
    "tim decoration",
    "fluent-emoji",
    "heart-decoration",
  ),
  item(
    "heart-hands",
    "Tay tạo tim",
    "hearts",
    "tim tay hands",
    "fluent-emoji",
    "heart-hands",
  ),
  item(
    "kiss-mark",
    "Nụ hôn",
    "hearts",
    "hon kiss",
    "fluent-emoji",
    "kiss-mark",
  ),
  item(
    "love-letter",
    "Thư tình",
    "hearts",
    "thu love letter",
    "fluent-emoji",
    "love-letter",
  ),
  item(
    "smiling-hearts",
    "Mặt cười tim",
    "hearts",
    "mat cuoi tim",
    "fluent-emoji",
    "smiling-face-with-hearts",
  ),
  item(
    "heart-eyes",
    "Mắt tim",
    "hearts",
    "mat tim love",
    "fluent-emoji",
    "smiling-face-with-heart-eyes",
  ),

  item("rose", "Hoa hồng", "flowers", "hoa hong rose", "fluent-emoji", "rose"),
  item("tulip", "Tulip", "flowers", "hoa tulip", "fluent-emoji", "tulip"),
  item(
    "hibiscus",
    "Dâm bụt",
    "flowers",
    "hoa hibiscus",
    "fluent-emoji",
    "hibiscus",
  ),
  item(
    "sunflower",
    "Hướng dương",
    "flowers",
    "hoa huong duong",
    "fluent-emoji",
    "sunflower",
  ),
  item(
    "blossom",
    "Hoa vàng",
    "flowers",
    "hoa blossom",
    "fluent-emoji",
    "blossom",
  ),
  item(
    "cherry",
    "Hoa anh đào",
    "flowers",
    "hoa anh dao sakura",
    "fluent-emoji",
    "cherry-blossom",
  ),
  item(
    "bouquet",
    "Bó hoa",
    "flowers",
    "bo hoa bouquet",
    "fluent-emoji",
    "bouquet",
  ),
  item(
    "white-flower",
    "Hoa trắng",
    "flowers",
    "hoa trang",
    "fluent-emoji",
    "white-flower",
  ),
  item("wilted", "Hoa héo", "flowers", "hoa", "fluent-emoji", "wilted-flower"),
  item("lotus", "Hoa sen", "flowers", "sen lotus", "fluent-emoji", "lotus"),
  item("hyacinth", "Lavender", "flowers", "hoa", "fluent-emoji", "hyacinth"),
  item(
    "rosette",
    "Hoa hồng huy",
    "flowers",
    "hoa rosette",
    "fluent-emoji",
    "rosette",
  ),
  item(
    "seedling",
    "Mầm cây",
    "flowers",
    "mam cay seedling",
    "fluent-emoji",
    "seedling",
  ),
  item(
    "potted",
    "Cây cảnh",
    "flowers",
    "cay canh pot",
    "fluent-emoji",
    "potted-plant",
  ),
  item("herb", "Lá thơm", "flowers", "la herb", "fluent-emoji", "herb"),
  item(
    "cherries",
    "Cherry",
    "flowers",
    "cherry qua",
    "fluent-emoji",
    "cherries",
  ),
  item("tulip-2", "Hoa tulip", "flowers", "hoa tulip", "fluent-emoji", "tulip"),

  item(
    "party-popper",
    "Pháo giấy",
    "party",
    "tiec party popper",
    "fluent-emoji",
    "party-popper",
  ),
  item(
    "confetti",
    "Confetti",
    "party",
    "tiec confetti",
    "fluent-emoji",
    "confetti-ball",
  ),
  item(
    "balloon",
    "Bóng bay",
    "party",
    "bong bay balloon",
    "fluent-emoji",
    "balloon",
  ),
  item("gift", "Hộp quà", "party", "qua gift", "fluent-emoji", "wrapped-gift"),
  item("ribbon", "Nơ", "party", "no ribbon", "fluent-emoji", "ribbon"),
  item(
    "clink",
    "Ly chạm",
    "party",
    "ly ruou cheers",
    "fluent-emoji",
    "clinking-glasses",
  ),
  item(
    "cork",
    "Rượu nổ",
    "party",
    "ruou champagne",
    "fluent-emoji",
    "bottle-with-popping-cork",
  ),
  item("wine", "Ly rượu", "party", "ruou wine", "fluent-emoji", "wine-glass"),
  item(
    "cocktail",
    "Cocktail",
    "party",
    "ruou cocktail",
    "fluent-emoji",
    "cocktail-glass",
  ),
  item(
    "tropical",
    "Đồ uống nhiệt đới",
    "party",
    "nuoc uong tropical",
    "fluent-emoji",
    "tropical-drink",
  ),
  item(
    "beer",
    "Ly bia",
    "party",
    "bia beer",
    "fluent-emoji",
    "clinking-beer-mugs",
  ),
  item(
    "fireworks",
    "Pháo hoa",
    "party",
    "phao hoa",
    "fluent-emoji",
    "fireworks",
  ),
  item(
    "sparkler",
    "Pháo bông",
    "party",
    "phao bong",
    "fluent-emoji",
    "sparkler",
  ),
  item(
    "notes",
    "Nốt nhạc",
    "party",
    "nhac music",
    "fluent-emoji",
    "musical-notes",
  ),
  item("note", "Nốt đơn", "party", "nhac note", "fluent-emoji", "musical-note"),
  item("headphones", "Tai nghe", "party", "nhac", "fluent-emoji", "headphone"),
  item("mic", "Micro", "party", "nhac micro", "fluent-emoji", "microphone"),
  item("guitar", "Guitar", "party", "nhac guitar", "fluent-emoji", "guitar"),
  item("violin", "Violin", "party", "nhac violin", "fluent-emoji", "violin"),
  item("drum", "Trống", "party", "nhac drum", "fluent-emoji", "drum"),
  item(
    "mirror-ball",
    "Đèn cầu",
    "party",
    "disco ball",
    "fluent-emoji",
    "mirror-ball",
  ),
  item("ticket", "Vé", "party", "ve ticket", "fluent-emoji", "ticket"),
  item(
    "admission",
    "Vé vào cửa",
    "party",
    "ve admission",
    "fluent-emoji",
    "admission-tickets",
  ),
  item(
    "arts",
    "Nghệ thuật",
    "party",
    "kich arts",
    "fluent-emoji",
    "performing-arts",
  ),
  item(
    "partying",
    "Mặt tiệc",
    "party",
    "mat tiec party",
    "fluent-emoji",
    "partying-face",
  ),
  item(
    "woman-dance",
    "Nhảy",
    "party",
    "nhay dance",
    "fluent-emoji",
    "woman-dancing",
  ),

  item("ring", "Nhẫn", "wedding", "nhan ring cuoi", "fluent-emoji", "ring"),
  item(
    "gem",
    "Kim cương",
    "wedding",
    "kim cuong gem",
    "fluent-emoji",
    "gem-stone",
  ),
  item(
    "wedding",
    "Nhà thờ",
    "wedding",
    "cuoi wedding",
    "fluent-emoji",
    "wedding",
  ),
  item(
    "church",
    "Nhà thờ",
    "wedding",
    "nha tho church",
    "fluent-emoji",
    "church",
  ),
  item("dove", "Bồ câu", "wedding", "bo cau dove", "fluent-emoji", "dove"),
  item(
    "veil",
    "Cô dâu",
    "wedding",
    "co dau bride",
    "fluent-emoji",
    "person-with-veil",
  ),
  item(
    "tux",
    "Chú rể",
    "wedding",
    "chu re tuxedo",
    "fluent-emoji",
    "person-in-tuxedo",
  ),
  item(
    "woman-veil",
    "Cô dâu",
    "wedding",
    "co dau veil",
    "fluent-emoji",
    "woman-with-veil",
  ),
  item(
    "man-tux",
    "Chú rể",
    "wedding",
    "chu re tuxedo",
    "fluent-emoji",
    "man-in-tuxedo",
  ),
  item(
    "hug",
    "Ôm nhau",
    "wedding",
    "om hug couple",
    "fluent-emoji",
    "people-hugging",
  ),
  item(
    "kiss-face",
    "Nụ hôn",
    "wedding",
    "hon kiss",
    "fluent-emoji",
    "kissing-face-with-closed-eyes",
  ),
  item(
    "folded",
    "Chắp tay",
    "wedding",
    "chap tay pray",
    "fluent-emoji",
    "folded-hands",
  ),
  item(
    "envelope",
    "Phong thư",
    "wedding",
    "thu envelope",
    "fluent-emoji",
    "envelope",
  ),
  item(
    "envelope-arrow",
    "Thư gửi",
    "wedding",
    "thu",
    "fluent-emoji",
    "envelope-with-arrow",
  ),
  item(
    "red-envelope",
    "Bao lì xì",
    "wedding",
    "li xi",
    "fluent-emoji",
    "red-envelope",
  ),
  item(
    "dolls",
    "Búp bê",
    "wedding",
    "bup be",
    "fluent-emoji",
    "japanese-dolls",
  ),
  item(
    "heels",
    "Giày cao gót",
    "wedding",
    "giay heel",
    "fluent-emoji",
    "high-heeled-shoe",
  ),
  item(
    "lipstick",
    "Son",
    "wedding",
    "son lipstick",
    "fluent-emoji",
    "lipstick",
  ),
  item(
    "bouquet-w",
    "Bó hoa cưới",
    "wedding",
    "bo hoa cuoi",
    "fluent-emoji",
    "bouquet",
  ),

  item(
    "grad-cap",
    "Mũ tốt nghiệp",
    "graduation",
    "tot nghiep cap",
    "fluent-emoji",
    "graduation-cap",
  ),
  item("trophy", "Cúp", "graduation", "cup trophy", "fluent-emoji", "trophy"),
  item(
    "medal",
    "Huy chương",
    "graduation",
    "huy chuong medal",
    "fluent-emoji",
    "sports-medal",
  ),
  item(
    "military-medal",
    "Huân chương",
    "graduation",
    "huan chuong",
    "fluent-emoji",
    "military-medal",
  ),
  item(
    "medal-1",
    "Huy chương vàng",
    "graduation",
    "vang gold medal",
    "fluent-emoji",
    "1st-place-medal",
  ),
  item(
    "medal-2",
    "Huy chương bạc",
    "graduation",
    "bac silver medal",
    "fluent-emoji",
    "2nd-place-medal",
  ),
  item(
    "medal-3",
    "Huy chương đồng",
    "graduation",
    "dong bronze medal",
    "fluent-emoji",
    "3rd-place-medal",
  ),
  item(
    "scroll",
    "Bằng khen",
    "graduation",
    "bang tot nghiep scroll",
    "fluent-emoji",
    "scroll",
  ),
  item("books", "Sách", "graduation", "sach book", "fluent-emoji", "books"),
  item(
    "open-book",
    "Sách mở",
    "graduation",
    "sach book",
    "fluent-emoji",
    "open-book",
  ),
  item(
    "pencil",
    "Bút chì",
    "graduation",
    "but pencil",
    "fluent-emoji",
    "pencil",
  ),
  item("memo", "Ghi chú", "graduation", "ghi chu memo", "fluent-emoji", "memo"),
  item(
    "bulb",
    "Bóng đèn",
    "graduation",
    "den y tuong",
    "fluent-emoji",
    "light-bulb",
  ),
  item(
    "hundred",
    "100 điểm",
    "graduation",
    "diem hundred",
    "fluent-emoji",
    "hundred-points",
  ),
  item(
    "school",
    "Trường",
    "graduation",
    "truong school",
    "fluent-emoji",
    "school",
  ),
  item(
    "student",
    "Sinh viên",
    "graduation",
    "sinh vien student",
    "fluent-emoji",
    "student",
  ),

  item(
    "cake",
    "Bánh kem",
    "birthday",
    "banh sinh nhat cake",
    "fluent-emoji",
    "birthday-cake",
  ),
  item(
    "shortcake",
    "Bánh ngọt",
    "birthday",
    "banh",
    "fluent-emoji",
    "shortcake",
  ),
  item(
    "cupcake",
    "Cupcake",
    "birthday",
    "banh cupcake",
    "fluent-emoji",
    "cupcake",
  ),
  item("balloon-b", "Bóng bay", "birthday", "bong", "fluent-emoji", "balloon"),
  item(
    "party-b",
    "Tiệc sinh nhật",
    "birthday",
    "sinh nhat",
    "fluent-emoji",
    "party-popper",
  ),
  item("candle", "Nến", "birthday", "nen candle", "fluent-emoji", "candle"),
  item(
    "lollipop",
    "Kẹo mút",
    "birthday",
    "keo lollipop",
    "fluent-emoji",
    "lollipop",
  ),
  item("candy", "Kẹo", "birthday", "keo candy", "fluent-emoji", "candy"),
  item(
    "ice-cream",
    "Kem ốc quế",
    "birthday",
    "kem ice cream",
    "fluent-emoji",
    "ice-cream",
  ),
  item(
    "soft-ice",
    "Kem mềm",
    "birthday",
    "kem",
    "fluent-emoji",
    "soft-ice-cream",
  ),
  item("cookie", "Cookie", "birthday", "banh cookie", "fluent-emoji", "cookie"),
  item(
    "doughnut",
    "Donut",
    "birthday",
    "banh doughnut",
    "fluent-emoji",
    "doughnut",
  ),
  item("pie", "Bánh pie", "birthday", "banh pie", "fluent-emoji", "pie"),
  item(
    "chocolate",
    "Sô cô la",
    "birthday",
    "socola chocolate",
    "fluent-emoji",
    "chocolate-bar",
  ),
  item(
    "gift-b",
    "Hộp quà",
    "birthday",
    "qua gift",
    "fluent-emoji",
    "wrapped-gift",
  ),
  item(
    "confetti-b",
    "Confetti",
    "birthday",
    "confetti",
    "fluent-emoji",
    "confetti-ball",
  ),

  item("baby", "Em bé", "baby", "be baby", "fluent-emoji", "baby"),
  item(
    "bottle",
    "Bình sữa",
    "baby",
    "sua bottle",
    "fluent-emoji",
    "baby-bottle",
  ),
  item("teddy", "Gấu bông", "baby", "gau teddy", "fluent-emoji", "teddy-bear"),
  item(
    "angel",
    "Thiên thần",
    "baby",
    "thien than angel",
    "fluent-emoji",
    "baby-angel",
  ),
  item(
    "footprints",
    "Bàn chân",
    "baby",
    "chan baby",
    "fluent-emoji",
    "footprints",
  ),
  item("chick", "Gà con", "baby", "ga con chick", "fluent-emoji", "baby-chick"),
  item(
    "hatch",
    "Trứng nở",
    "baby",
    "trung hatch",
    "fluent-emoji",
    "hatching-chick",
  ),
  item(
    "front-chick",
    "Gà con mặt",
    "baby",
    "ga con",
    "fluent-emoji",
    "front-facing-baby-chick",
  ),
  item("yarn", "Len", "baby", "len yarn", "fluent-emoji", "yarn"),
  item(
    "safety-pin",
    "Kim băng",
    "baby",
    "kim bang pin",
    "fluent-emoji",
    "safety-pin",
  ),
  item(
    "nest-eggs",
    "Tổ trứng",
    "baby",
    "to trung nest",
    "fluent-emoji",
    "nest-with-eggs",
  ),
  item(
    "baby-symbol",
    "Biểu tượng bé",
    "baby",
    "be symbol",
    "fluent-emoji",
    "baby-symbol",
  ),
  item("ribbon-b", "Nơ", "baby", "no ribbon", "fluent-emoji", "ribbon"),
  item("cloud-b", "Mây", "baby", "may cloud", "fluent-emoji", "cloud"),

  item(
    "butterfly",
    "Bướm",
    "nature",
    "buom butterfly",
    "fluent-emoji",
    "butterfly",
  ),
  item(
    "leaf-clover",
    "Cỏ bốn lá",
    "nature",
    "co four leaf",
    "fluent-emoji",
    "four-leaf-clover",
  ),
  item(
    "shamrock",
    "Cỏ ba lá",
    "nature",
    "co shamrock",
    "fluent-emoji",
    "shamrock",
  ),
  item("maple", "Lá phong", "nature", "la maple", "fluent-emoji", "maple-leaf"),
  item("fallen", "Lá rơi", "nature", "la", "fluent-emoji", "fallen-leaf"),
  item(
    "leaf-wind",
    "Lá gió",
    "nature",
    "la gio",
    "fluent-emoji",
    "leaf-fluttering-in-wind",
  ),
  item("palm", "Cọ", "nature", "co palm", "fluent-emoji", "palm-tree"),
  item(
    "evergreen",
    "Thông",
    "nature",
    "thong tree",
    "fluent-emoji",
    "evergreen-tree",
  ),
  item(
    "deciduous",
    "Cây lá",
    "nature",
    "cay tree",
    "fluent-emoji",
    "deciduous-tree",
  ),
  item(
    "cactus",
    "Xương rồng",
    "nature",
    "xuong rong cactus",
    "fluent-emoji",
    "cactus",
  ),
  item(
    "rainbow",
    "Cầu vồng",
    "nature",
    "cau vong rainbow",
    "fluent-emoji",
    "rainbow",
  ),
  item(
    "moon",
    "Trăng",
    "nature",
    "trang moon",
    "fluent-emoji",
    "crescent-moon",
  ),
  item(
    "full-moon",
    "Trăng tròn",
    "nature",
    "trang moon",
    "fluent-emoji",
    "full-moon-face",
  ),
  item(
    "sun",
    "Mặt trời",
    "nature",
    "mat troi sun",
    "fluent-emoji",
    "sun-with-face",
  ),
  item(
    "cloud",
    "Mây",
    "nature",
    "may cloud",
    "fluent-emoji",
    "sun-behind-cloud",
  ),
  item("wave", "Sóng", "nature", "song wave", "fluent-emoji", "water-wave"),
  item("bee", "Ong", "nature", "ong bee", "fluent-emoji", "honeybee"),
  item("ladybug", "Bọ rùa", "nature", "bo rua", "fluent-emoji", "lady-beetle"),
  item("bird", "Chim", "nature", "chim bird", "fluent-emoji", "bird"),
  item(
    "flamingo",
    "Hồng hạc",
    "nature",
    "hong hac flamingo",
    "fluent-emoji",
    "flamingo",
  ),
  item("swan", "Thiên nga", "nature", "thien nga swan", "fluent-emoji", "swan"),
  item(
    "snowflake",
    "Bông tuyết",
    "nature",
    "tuyet snow",
    "fluent-emoji",
    "snowflake",
  ),
  item("mushroom", "Nấm", "nature", "nam mushroom", "fluent-emoji", "mushroom"),

  item(
    "sparkles",
    "Lấp lánh",
    "stars",
    "lap lanh sparkle",
    "fluent-emoji",
    "sparkles",
  ),
  item(
    "sparkle",
    "Tia sáng",
    "stars",
    "tia sparkle",
    "fluent-emoji",
    "sparkle",
  ),
  item(
    "star-glow",
    "Sao sáng",
    "stars",
    "sao star",
    "fluent-emoji",
    "glowing-star",
  ),
  item("star", "Ngôi sao", "stars", "sao", "fluent-emoji", "star"),
  item("dizzy", "Sao xoay", "stars", "sao", "fluent-emoji", "dizzy"),
  item(
    "night",
    "Đêm sao",
    "stars",
    "dem sao",
    "fluent-emoji",
    "night-with-stars",
  ),
  item(
    "shooting",
    "Sao băng",
    "stars",
    "sao bang",
    "fluent-emoji",
    "shooting-star",
  ),
  item("comet", "Sao chổi", "stars", "sao choi comet", "fluent-emoji", "comet"),
  item(
    "eight-star",
    "Sao tám cánh",
    "stars",
    "sao",
    "fluent-emoji",
    "eight-pointed-star",
  ),
  item(
    "crown",
    "Vương miện",
    "stars",
    "vuong mien crown",
    "fluent-emoji",
    "crown",
  ),
  item("sparkler-s", "Pháo sáng", "stars", "phao", "fluent-emoji", "sparkler"),
  item(
    "crystal",
    "Quả cầu",
    "stars",
    "cau crystal",
    "fluent-emoji",
    "crystal-ball",
  ),
  item(
    "wand",
    "Đũa phép",
    "stars",
    "dua phep wand",
    "fluent-emoji",
    "magic-wand",
  ),
  item(
    "star-struck",
    "Mắt sao",
    "stars",
    "mat sao",
    "fluent-emoji",
    "star-struck",
  ),

  item(
    "orn-heart",
    "Tim nét",
    "ornament",
    "hoa tiet heart line",
    "lucide",
    "heart",
  ),
  item(
    "orn-sparkle",
    "Tia lấp lánh",
    "ornament",
    "hoa tiet sparkle",
    "lucide",
    "sparkle",
  ),
  item(
    "orn-sparkles",
    "Lấp lánh nét",
    "ornament",
    "hoa tiet sparkles",
    "lucide",
    "sparkles",
  ),
  item("orn-star", "Sao nét", "ornament", "hoa tiet star", "lucide", "star"),
  item(
    "orn-flower",
    "Hoa nét",
    "ornament",
    "hoa tiet flower",
    "lucide",
    "flower-2",
  ),
  item("orn-leaf", "Lá nét", "ornament", "hoa tiet leaf", "lucide", "leaf"),
  item(
    "orn-crown",
    "Vương miện nét",
    "ornament",
    "hoa tiet crown",
    "lucide",
    "crown",
  ),
  item("orn-gem", "Kim cương nét", "ornament", "hoa tiet gem", "lucide", "gem"),
  item(
    "orn-music",
    "Nhạc nét",
    "ornament",
    "hoa tiet music",
    "lucide",
    "music",
  ),
  item(
    "orn-camera",
    "Máy ảnh nét",
    "ornament",
    "hoa tiet camera",
    "lucide",
    "camera",
  ),
  item("orn-gift", "Quà nét", "ornament", "hoa tiet gift", "lucide", "gift"),
  item("orn-mail", "Thư nét", "ornament", "hoa tiet mail", "lucide", "mail"),
  item("orn-map", "Ghim nét", "ornament", "hoa tiet map", "lucide", "map-pin"),
  item("orn-cake", "Bánh nét", "ornament", "hoa tiet cake", "lucide", "cake"),
  item("orn-baby", "Bé nét", "ornament", "hoa tiet baby", "lucide", "baby"),
  item(
    "orn-grad",
    "Mũ tốt nghiệp nét",
    "ornament",
    "hoa tiet tot nghiep",
    "lucide",
    "graduation-cap",
  ),
  item(
    "orn-party",
    "Tiệc nét",
    "ornament",
    "hoa tiet party",
    "lucide",
    "party-popper",
  ),
  item(
    "orn-church",
    "Nhà thờ nét",
    "ornament",
    "hoa tiet church",
    "lucide",
    "church",
  ),
  item(
    "orn-wine",
    "Ly rượu nét",
    "ornament",
    "hoa tiet wine",
    "lucide",
    "wine",
  ),
  item("orn-sun", "Mặt trời nét", "ornament", "hoa tiet sun", "lucide", "sun"),
  item("orn-moon", "Trăng nét", "ornament", "hoa tiet moon", "lucide", "moon"),
  item(
    "orn-cloud",
    "Mây nắng nét",
    "ornament",
    "hoa tiet cloud",
    "lucide",
    "cloud-sun",
  ),
  item("orn-bird", "Chim nét", "ornament", "hoa tiet bird", "lucide", "bird"),
  item(
    "orn-butterfly",
    "Origami nét",
    "ornament",
    "hoa tiet origami butterfly",
    "lucide",
    "origami",
  ),
  item(
    "orn-clover",
    "Cỏ nét",
    "ornament",
    "hoa tiet clover",
    "lucide",
    "clover",
  ),
  item(
    "orn-diamond",
    "Kim cương nét",
    "ornament",
    "hoa tiet diamond",
    "lucide",
    "diamond",
  ),
  item(
    "orn-frame",
    "Khung nét",
    "ornament",
    "hoa tiet frame",
    "lucide",
    "frame",
  ),
  item(
    "orn-bookmark",
    "Đánh dấu nét",
    "ornament",
    "hoa tiet bookmark",
    "lucide",
    "bookmark",
  ),
  item(
    "orn-heart-hand",
    "Bắt tay tim",
    "ornament",
    "hoa tiet handshake",
    "lucide",
    "heart-handshake",
  ),
  item(
    "orn-trees",
    "Rừng nét",
    "ornament",
    "hoa tiet trees",
    "lucide",
    "trees",
  ),
  item(
    "orn-mountain",
    "Núi nét",
    "ornament",
    "hoa tiet mountain",
    "lucide",
    "mountain",
  ),
  item(
    "orn-waves",
    "Sóng nét",
    "ornament",
    "hoa tiet waves",
    "lucide",
    "waves-horizontal",
  ),
  item("orn-key", "Chìa khóa nét", "ornament", "hoa tiet key", "lucide", "key"),
  item(
    "orn-calendar",
    "Lịch nét",
    "ornament",
    "hoa tiet calendar",
    "lucide",
    "calendar",
  ),
  item("orn-home", "Nhà nét", "ornament", "hoa tiet home", "lucide", "house"),
];

export const GRAPHIC_STICKERS = STOCK_STICKERS.filter(
  (item) => item.kind === "sticker",
);
export const ORNAMENT_STICKERS = STOCK_STICKERS.filter(
  (item) => item.kind === "ornament",
);

export const EXTRA_EMOJI_CATEGORIES = [
  {
    name: "Tốt nghiệp",
    emojis: ["🎓", "📜", "🏆", "🏅", "📚", "✏️", "🎉", "🥳"],
  },
  {
    name: "Sinh nhật",
    emojis: ["🎂", "🧁", "🎈", "🎁", "🥳", "🕯️", "🎶", "📸"],
  },
  {
    name: "Baby",
    emojis: ["👶", "🍼", "🧸", "💛", "👣", "🎀", "☁️", "🌙"],
  },
  {
    name: "Khai trương",
    emojis: ["🏪", "✂️", "🎊", "🥂", "🔑", "📍", "✨", "📣"],
  },
];
