export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: "/api/user/auth/login",
    SEND_OTP_REGISTRATION: "/api/user/auth/send-otp",
    SEND_OTP_VERIFY: "/api/user/auth/send-otp-verify",
    VERIFY_OTP: "/api/user/auth/verify-otp",
    REGISTER: "/api/user/auth/register",
    FORGOT_PASSWORD: "/api/user/auth/forgot-password",
    LOGIN_GOOGLE: "/api/user/auth/login/google",
    LOGIN_FACEBOOK: "/api/user/auth/login/facebook",
    LOGOUT: "/api/user/auth/logout",
    REFRESH_TOKEN: "/api/user/auth/refresh-token",
    ME: "/api/user/auth/me",
    CHANGE_PASSWORD: "/api/user/auth/change-password",
    UPDATE_PASSWORD: "/api/user/auth/update-password",
    CHECK_PHONE_EMAIL: "/api/user/auth/check-phone-email",
    VERIFY_EMAIL: "/api/user/auth/verify-email",
    RESEND_VERIFICATION: "/api/user/auth/resend-verification",
    CLEAN_TOKENS: "/api/user/auth/clean-tokens",
    UPDATE_PROFILE: "/api/user/auth/update-profile",
  },
  SERVICE_PLAN: {
    PUBLIC_LIST: "/api/user/service-plan/public/list",
  },
  CONTACT: {
    CREATE: "/api/user/contact/public/create",
  },
  TEMPLATE: {
    PAGINATION: "/api/user/template/pagination",
    INCREMENT_VIEW: "/api/user/template/increment-view",
    INCREMENT_PREVIEW: "/api/user/template/increment-preview",
  },
  WEDDING: {
    CREATE: "/api/user/wedding/create",
    UPDATE: "/api/user/wedding/update",
    PUBLISH: "/api/user/wedding/publish",
    UNPUBLISH: "/api/user/wedding/unpublish",
    FIND_BY_ID: "/api/user/wedding/find-by-id",
    FIND_BY_SLUG: "/api/user/wedding/public/find-by-slug",
    PAGINATION: "/api/user/wedding/pagination",
  },
  UPLOAD_FILE: {
    IMAGE: "/api/upload/upload-file/upload-image",
    BULK_IMAGES: "/api/upload/upload-file/upload-multi",
    AUDIO: "/api/upload/upload-file/upload-audio",
  },
  MUSIC_BACKGROUND: {
    FIND_ALL_ACTIVATE: "/api/user/music-background/active",
    IMPORT_YOUTUBE: "/api/user/music-background/import-youtube",
    INCREMENT_USAGE: "/api/user/music-background/increment-usage",
  },
  GIPHY: {
    SEARCH: "/api/user/giphy/search",
    PEXELS_SEARCH: "/api/user/giphy/pexels-search",
  },
  GUEST: {
    PAGINATION: "/api/user/guest/pagination",
    FIND_BY_ID: "/api/user/guest/find-by-id",
    CREATE: "/api/user/guest/create",
    CREATE_MANY: "/api/user/guest/create-many",
    UPDATE: "/api/user/guest/update",
    DELETE: "/api/user/guest/delete",
    GENERATE_QR: "/api/user/guest/generate-qr",
    IMPORT_EXCEL: "/api/user/guest/import-excel",
    DOWNLOAD_SAMPLE_EXCEL: "/api/user/guest/download-sample-excel",
    PUBLIC_IDENTIFY: "/api/user/guest/public/identify",
    PUBLIC_RSVP: "/api/user/guest/public/rsvp",
  },

  WISH: {
    PAGINATION: "/api/user/wish/pagination",
    CREATE: "/api/user/wish/create",
    APPROVE: "/api/user/wish/approve",
    REJECT: "/api/user/wish/reject",
    PIN: "/api/user/wish/pin",
    UNPIN: "/api/user/wish/unpin",
    DELETE: "/api/user/wish/delete",
  },
  TABLE: {
    PAGINATION: "/api/user/table/pagination",
    FIND_BY_ID: "/api/user/table/find-by-id",
    CREATE: "/api/user/table/create",
    UPDATE: "/api/user/table/update",
    DELETE: "/api/user/table/delete",
    ASSIGN_GUEST: "/api/user/table/assign-guest",
    UNASSIGN_GUEST: "/api/user/table/unassign-guest",
  },
  MAP: {
    RESOLVE_URL: "/api/resolve-map-url",
  },
};
